kind: JVMChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: k8s-helidon-app
  name: jvm-cpu-stress
spec:
  selector:
    namespaces:
      - k8s-helidon-app
    labelSelectors:
      app: k8s-helidon-app
  mode: one
  duration: 2m
  action: stress
  port: 9277
  cpuCount: 4
  name: "--stress-1652168099"
  value: ""
  exception: ""
  latency: 0
  ruleData: ""
