kind: JVMChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: k8s-helidon-app
  name: jvm-runtime-exception
spec:
  selector:
    namespaces:
      - k8s-helidon-app
    labelSelectors:
      app: k8s-helidon-app
  mode: one
  duration: 2m
  action: exception
  port: 9277
  class: me.shukawam.GreetingProvider
  method: getMessage
  name: me.shukawam.GreetingProvider-getMessage-exception-1652170845
  value: ""
  exception: java.lang.RuntimeException("BOOM")
  latency: 0
  ruleData: ""
