kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ochacafe
  name: pod-kill
spec:
  selector:
    namespaces:
      - ochacafe
    labelSelectors:
      app: wordpress
  mode: one
  action: pod-kill
  gracePeriod: 0